-- Packing list per trip. Generated by the agent based on trip length,
-- weather forecast, and activities. `reasoning` captures why the agent
-- suggested each item (e.g. "rain expected Wed-Fri" → "waterproof jacket").

CREATE TABLE IF NOT EXISTS packing_items (
    id           BIGSERIAL PRIMARY KEY,
    trip_id      BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    item         VARCHAR(255) NOT NULL,
    category     VARCHAR(64),                           -- clothing, toiletries, electronics, documents, weather_gear, activity_gear
    is_packed    BOOLEAN DEFAULT FALSE,
    generated_by VARCHAR(32),                           -- user, agent
    reasoning    TEXT,                                  -- why the agent suggested this
    created_at   TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_packing_trip ON packing_items(trip_id);
